version: '3'

services:
  node:
    container_name: node
    image: konkeydong/node:latest
    stdin_open: true
    tty: true
    network_mode: bridge
    ports: 
      -  8081:8081
    build: ./node
    volumes:
      - ./node/:/usr/src/app

  postgres:
    container_name: postgres
    image: konkeydong/postgres:latest
    stdin_open: true
    tty: true
    ports: 
      -  5432:5432
    network_mode: bridge
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    build: ./postgres
    volumes:
      - ./postgres/db/:/root/db/
      - ./postgres/bin/:/root/bin/
      - $HOME/docker/volumes/postgres/:/var/lib/postgresql/data
