version: '3'

services:
  node:
    container_name: node
    image: konkeydong/node:latest
    stdin_open: true
    tty: true
    ports: 
      -  8081:8081
    build: ./node
    networks:
      - the_net
    volumes:
      - ./node/:/usr/src/app

  mysql:
    container_name: mysql
    image: konkeydong/mysql:latest
    stdin_open: true
    tty: true
    ports: 
      -  3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=expense_report
    build: ./mysql
    networks:
      - the_net
    volumes:
      - ./mysql/db/:/app/db/
      - data:/var/lib/mysql

networks:
  the_net:

volumes:
  data: