version: '3'

services:
  node:
    container_name: node
    image: konkeydong/node:latest
    stdin_open: true
    tty: true
    ports: 
      -  8081:8081
    build: ./node
    networks:
      - the_net
    volumes:
      - ./node/:/usr/src/app

  postgres:
    container_name: postgres
    image: konkeydong/postgres:latest
    stdin_open: true
    tty: true
    ports: 
      -  5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    build: ./postgres
    networks:
      - the_net
    volumes:
      - ./postgres/db/:/app/db/
      - $HOME/docker/volumes/postgres/:/var/lib/postgresql/data

networks:
  the_net: